server:
  port: 8080

spring:
  application:
    name: newsApplication
  datasource:
    url: jdbc:mysql://localhost:3306/test_db?serverTimezone=UTC
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
springdoc:
  swagger-ui:
    path : /swagger-ui.html